#include "Component.hpp"
#include "../../core/Limits.hpp"
#include <algorithm>
#include <sstream>
namespace DiscordBridge { namespace {
std::string Esc(const std::string&s){std::string o;o.reserve(s.size()+8);for(char c:s){switch(c){case '"':o+="\\\"";break;case '\\':o+="\\\\";break;case '\n':o+="\\n";break;case '\r':o+="\\r";break;case '\t':o+="\\t";break;default:o+=c;}}return o;}
bool IsSelect(int t){return t==3||(t>=5&&t<=8);} bool IsModalInput(int t){return t==3||t==4||(t>=5&&t<=8)||t==19||t==21||t==22||t==23;}
bool Allowed(int p,int c){if(p==1)return c==2||IsSelect(c);if(p==17)return c==1||c==9||c==10||c==12||c==13||c==14;if(p==9)return c==10;if(p==18)return IsModalInput(c);return false;}
}
bool Component::setCustomId(const std::string&v){if(v.empty()||v.size()>Limits::MaxCustomIdLength)return false;customId_=v;return true;}
bool Component::setLabel(const std::string&v){if(v.empty()||v.size()>100)return false;label_=v;return true;} bool Component::setDescription(const std::string&v){if(v.size()>100)return false;description_=v;return true;}
bool Component::setContent(const std::string&v){if(v.empty()||v.size()>4000)return false;content_=v;return true;} bool Component::setPlaceholder(const std::string&v){if(v.size()>150)return false;placeholder_=v;return true;} bool Component::setValue(const std::string&v){if(v.size()>4000)return false;value_=v;return true;} bool Component::setUrl(const std::string&v){if(v.empty()||v.size()>2048)return false;url_=v;return true;} bool Component::setEmoji(const std::string&v){if(v.size()>128)return false;emoji_=v;return true;} bool Component::setSkuId(const std::string&v){if(v.empty()||v.size()>20||!std::all_of(v.begin(),v.end(),::isdigit))return false;skuId_=v;return true;}
bool Component::setStyle(int v){if(type_==2){if(v<1||v>6)return false;}else if(type_==4){if(v<1||v>2)return false;}else return false;style_=v;return true;} bool Component::setRange(int a,int b){if(a<0||b<1||a>b||b>25)return false;minValues_=a;maxValues_=b;return true;} bool Component::setLength(int a,int b){if(a<0||b<1||a>b||b>4000)return false;minLength_=a;maxLength_=b;return true;} bool Component::setAccentColor(int v){if(type_!=17||v<0||v>0xFFFFFF)return false;accentColor_=v;return true;} bool Component::setSpacing(int v){if(type_!=14||v<1||v>2)return false;spacing_=v;return true;}
bool Component::addOption(const std::string&l,const std::string&v,const std::string&d,const std::string&e,bool def){if(!(type_==3||type_==21||type_==22)||l.empty()||v.empty()||options_.size()>=25||l.size()>100||v.size()>100||d.size()>100)return false;options_.push_back({l,v,d,e,def});return true;} bool Component::addMedia(const std::string&u,const std::string&d,bool s){if(type_!=12||u.empty()||media_.size()>=10)return false;media_.push_back({u,d,s});return true;} bool Component::addChannelType(int t){if(type_!=8||t<0||t>16)return false;if(std::find(channelTypes_.begin(),channelTypes_.end(),t)==channelTypes_.end())channelTypes_.push_back(t);return true;}
bool Component::addChild(ComponentHandle h,const ComponentManager&m){auto*c=m.get(h);if(!c||!Allowed(type_,c->type())||std::find(children_.begin(),children_.end(),h)!=children_.end())return false;if(type_==1){if(IsSelect(c->type())&&!children_.empty())return false;if(c->type()==2&&(!children_.empty()&&m.get(children_[0])->type()!=2))return false;if(children_.size()>=5)return false;}if(type_==9&&children_.size()>=3)return false;if(type_==18&&!children_.empty())return false;children_.push_back(h);return true;}
bool Component::setAccessory(ComponentHandle h,const ComponentManager&m){auto*c=m.get(h);if(type_!=9||!c||(c->type()!=2&&c->type()!=11))return false;accessory_=h;return true;}
std::string Component::toJson(const ComponentManager&m)const{std::ostringstream j;j<<"{\"type\":"<<type_;if(!customId_.empty())j<<",\"custom_id\":\""<<Esc(customId_)<<"\"";if(!label_.empty()&&type_!=4)j<<",\"label\":\""<<Esc(label_)<<"\"";if(!description_.empty())j<<",\"description\":\""<<Esc(description_)<<"\"";if(!content_.empty())j<<",\"content\":\""<<Esc(content_)<<"\"";if(!placeholder_.empty())j<<",\"placeholder\":\""<<Esc(placeholder_)<<"\"";if(!value_.empty())j<<",\"value\":\""<<Esc(value_)<<"\"";if(type_==2){j<<",\"style\":"<<style_;if(style_==5&&!url_.empty())j<<",\"url\":\""<<Esc(url_)<<"\"";if(style_==6&&!skuId_.empty())j<<",\"sku_id\":\""<<Esc(skuId_)<<"\"";if(!emoji_.empty())j<<",\"emoji\":{\"name\":\""<<Esc(emoji_)<<"\"}";j<<",\"disabled\":"<<(disabled_?"true":"false");}if(type_==4){j<<",\"style\":"<<style_<<",\"min_length\":"<<minLength_<<",\"max_length\":"<<maxLength_<<",\"required\":"<<(required_?"true":"false");}if(IsSelect(type_)||type_==19||type_==21||type_==22){j<<",\"min_values\":"<<minValues_<<",\"max_values\":"<<maxValues_<<",\"required\":"<<(required_?"true":"false");if(IsSelect(type_))j<<",\"disabled\":"<<(disabled_?"true":"false");}if(type_==23)j<<",\"required\":"<<(required_?"true":"false");if(type_==17){if(accentColor_>=0)j<<",\"accent_color\":"<<accentColor_;j<<",\"spoiler\":"<<(spoiler_?"true":"false");}if(type_==14)j<<",\"divider\":"<<(divider_?"true":"false")<<",\"spacing\":"<<spacing_;if(type_==11&&!url_.empty())j<<",\"media\":{\"url\":\""<<Esc(url_)<<"\"},\"spoiler\":"<<(spoiler_?"true":"false");if(type_==13&&!url_.empty())j<<",\"file\":{\"url\":\""<<Esc(url_)<<"\"},\"spoiler\":"<<(spoiler_?"true":"false");if(!options_.empty()){j<<",\"options\":[";for(size_t i=0;i<options_.size();++i){if(i)j<<',';auto&o=options_[i];j<<"{\"label\":\""<<Esc(o.label)<<"\",\"value\":\""<<Esc(o.value)<<"\"";if(!o.description.empty())j<<",\"description\":\""<<Esc(o.description)<<"\"";if(!o.emoji.empty())j<<",\"emoji\":{\"name\":\""<<Esc(o.emoji)<<"\"}";if(o.isDefault)j<<",\"default\":true";j<<'}';}j<<']';}if(!channelTypes_.empty()){j<<",\"channel_types\":[";for(size_t i=0;i<channelTypes_.size();++i){if(i)j<<',';j<<channelTypes_[i];}j<<']';}if(type_==12&&!media_.empty()){j<<",\"items\":[";for(size_t i=0;i<media_.size();++i){if(i)j<<',';auto&x=media_[i];j<<"{\"media\":{\"url\":\""<<Esc(x.url)<<"\"}";if(!x.description.empty())j<<",\"description\":\""<<Esc(x.description)<<"\"";if(x.spoiler)j<<",\"spoiler\":true";j<<'}';}j<<']';}if(type_==18&&!children_.empty()){auto*c=m.get(children_[0]);if(c)j<<",\"component\":"<<c->toJson(m);}else if(!children_.empty()){j<<",\"components\":[";bool first=true;for(auto h:children_){auto*c=m.get(h);if(!c)continue;if(!first)j<<',';first=false;j<<c->toJson(m);}j<<']';}if(type_==9&&accessory_){auto*c=m.get(accessory_);if(c)j<<",\"accessory\":"<<c->toJson(m);}j<<'}';return j.str();}
ComponentHandle ComponentManager::create(int t){if(t<1||t>23||t==15||t==16||t==20||components_.size()>=4096)return 0;while(next_==0||components_.count(next_))++next_;auto h=next_++;components_.emplace(h,std::make_unique<Component>(t));return h;} bool ComponentManager::destroy(ComponentHandle h){return components_.erase(h)>0;} Component*ComponentManager::get(ComponentHandle h){auto i=components_.find(h);return i==components_.end()?nullptr:i->second.get();} const Component*ComponentManager::get(ComponentHandle h)const{auto i=components_.find(h);return i==components_.end()?nullptr:i->second.get();} void ComponentManager::clear(){components_.clear();next_=1;}
}
